version: "3"

services:
  portainer:
    image: portainer/portainer-ce:alpine
    restart: always
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/portainer_data:/data
