version: "3"

services:
  postgres:
    image: postgres:16-bullseye
    restart: always
    container_name: postgres-1
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - $PWD/postgres_data:/var/lib/postgresql/data
